name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: verify_versions
        id: verify
        continue-on-error: true
        run: |
          python script/verify.py
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: push_metadata_file
        if: steps.verify.outcome == 'success'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: commit meta
          branch: ${{ steps.extract_branch.outputs.branch }}
      - name: revert failed migration
        if: steps.verify.outcome == 'failure'
        id: revert
        run: |
          git config --global user.name "CHECKER"
          git log
          git revert HEAD
          git log
      - name: push_metadata_file
        if: steps.revert.outcome == 'success'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: commit meta
          branch: ${{ steps.extract_branch.outputs.branch }}
          
